//! Post-processing of generated HTML: footnote and cross-reference handling.
//!
//! These functions operate on HTML that has already been generated by the main
//! marker-processing loop in `convertVerseEntryListToHtml`.  They replace raw
//! USFM markers (`\f…\f*` and `\x…\x*`) with live HTML links and collect the
//! content into footnotes / cross-reference sections appended to the output.

use crate::constants::SPAN_CLASS_REGEX;
use crate::xref_links::liven_xref_field_core;

// ── Error type ─────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum VerseToHtmlError {
    /// A required end marker (e.g. `\x*`, `\f*`) was not found.
    MissingEndMarker { marker: String, position: usize },
    /// An internal parsing inconsistency.
    UnexpectedContent { details: String },
    /// The liven_xref_field callback failed.
    CallbackFailed { details: String },
}

impl std::fmt::Display for VerseToHtmlError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingEndMarker { marker, position } => {
                write!(f, "missing end marker '{marker}' at position {position}")
            }
            Self::UnexpectedContent { details } => write!(f, "{details}"),
            Self::CallbackFailed { details } => write!(f, "callback failed: {details}"),
        }
    }
}

impl std::error::Error for VerseToHtmlError {}

// ── Helper: compute the path prefix used in links ──────────────────────────

/// Compute the `pathPrefix` that the Python code derives from `segmentType`.
pub fn compute_path_prefix(segment_type: &str) -> &'static str {
    match segment_type {
        "parallelVerse" | "interlinearVerse" => "../../OET/byC/",
        "topicalPassage" => "../OET/byC/",
        "chapter" => "",
        _ => "../byC/",
    }
}

// ── Cross-reference processing ─────────────────────────────────────────────

/// Process all `\x…\x*` cross-reference markers in `html`, replacing them
/// with caller links and collecting the content into a cross-references HTML
/// block.
///
/// Returns `(modified_html, cross_references_html)`.
pub fn process_cross_references_core<F>(
    html: &str,
    version_abbrev: &str,
    bbb: &str,
    c: &str,
    segment_type: &str,
    path_prefix: &str,
    find_section_fn: F,
) -> Result<(String, String), VerseToHtmlError>
where
    F: Fn(&str, &str, &str, &str) -> Option<usize>,
{
    let mut result_html = html.to_string();
    let mut xr_count: usize = 0;
    let mut xr_html = String::new();
    let mut search_ix: usize = 0;
    let mut last_search_ix: usize = usize::MAX;

    let max_iter = if segment_type == "book" { 599 } else { 99 };

    for _ in 0..max_iter {
        if search_ix == last_search_ix {
            break; // no progress → avoid infinite loop
        }
        last_search_ix = search_ix;

        let x_start = match result_html[search_ix..].find("\\x ") {
            Some(ix) => search_ix + ix,
            None => break,
        };
        xr_count += 1;

        // --- Locate \xo (optional) and \xt (required) ---
        let after_x = x_start + 3;
        let xt_ix = result_html[after_x..]
            .find("\\xt ")
            .map(|ix| after_x + ix)
            .ok_or_else(|| VerseToHtmlError::MissingEndMarker {
                marker: "\\xt".into(),
                position: after_x,
            })?;

        let xo_ix = result_html[after_x..]
            .find("\\xo ")
            .map(|ix| after_x + ix)
            .filter(|&ix| ix < xt_ix);

        let xo_text = if let Some(xo_ix) = xo_ix {
            result_html[xo_ix + 3..xt_ix].trim().to_string()
        } else {
            String::new()
        };

        let x_end = result_html[xt_ix + 3..]
            .find("\\x*")
            .map(|ix| xt_ix + 3 + ix)
            .ok_or_else(|| VerseToHtmlError::MissingEndMarker {
                marker: "\\x*".into(),
                position: xt_ix + 3,
            })?;

        // --- Extract & liven the xref content ---
        let raw_middle = &result_html[xt_ix + 4..x_end];
        let original_middle = raw_middle
            .replace("\\xo ", "")
            .replace("\\xt ", "");
        let mut live_middle = raw_middle
            .replace("\\xo ", "<b>")
            .replace("\\xt ", "</b>");

        live_middle = liven_xref_field_core(
            "x",
            version_abbrev,
            bbb,
            c,
            "",
            segment_type,
            path_prefix,
            &xo_text,
            &live_middle,
            &find_section_fn,
        )
        .map_err(|e| VerseToHtmlError::CallbackFailed { details: e.to_string() })?;

        // --- Build caller span ---
        let caller = format!(
            r##"<span class="xrCaller">[<a title="See also {original_middle}" href="#xr{xr_count}">ref</a>]</span>"##
        );

        // --- Build back-reference (from the xref section to the caller) ---
        let xr_ref = build_cv_ref(&xo_text);

        let xref_text = format!(
            r##"<p class="xr" id="xr{xr_count}">{xr_ref}<span class="xrText">{live_middle}</span></p><!--xr-->"##
        );
        xr_html.push_str(&xref_text);

        // --- Splice the caller into the HTML ---
        result_html = format!(
            "{}{}{}",
            &result_html[..x_start],
            caller,
            &result_html[x_end + 3..]
        );
        search_ix = x_start + caller.len();
    }

    Ok((result_html, xr_html))
}

/// Build a `<span class="xrRef">…</span>` back-reference from `\xo` text.
///
/// E.g. `"1:1-3"` → `<span class="xrRef"><a title="Return to text" href="#C1V1">1:1-3</a></span> `
fn build_cv_ref(xo_text: &str) -> String {
    if xo_text.is_empty() {
        return String::new();
    }
    let mut cv = xo_text.to_string();
    if cv.contains('-') || cv.contains('\u{2013}') {
        // en-dash → hyphen, then take part before first dash
        cv = cv.replace('\u{2013}', "-");
        if let Some(ix) = cv.find('-') {
            cv = cv[..ix].to_string();
        }
    }
    if let Some(colon_ix) = cv.find(':') {
        let ch = &cv[..colon_ix];
        let mut v = &cv[colon_ix + 1..];
        if let Some(inner) = v.find(':') {
            v = &v[..inner];
        }
        format!(
            r##"<span class="xrRef"><a title="Return to text" href="#C{ch}V{v}">{xo_text}</a></span> "##
        )
    } else {
        // No colon – unusual, produce link without href
        format!(
            r#"<span class="xrRef"><a title="Return to text" href="">{xo_text}</a></span> "#
        )
    }
}

// ── Footnote processing ────────────────────────────────────────────────────

/// Process all `\f…\f*` footnote markers in `html`, replacing them with
/// caller links and collecting the content into a footnotes HTML block.
///
/// TODO: We don't yet compare the contents of the fr text to the current verse reference (to help detect human errors in the USFM)
///         We will need the whole referenceTuple to do that, so it probably needs to be passed as a parameter instead of just bbb and c
/// 
/// Returns `(modified_html, footnotes_html)`.
pub fn process_footnotes_core<F>(
    html: &str,
    version_abbrev: &str,
    bbb: &str,
    c: &str,
    segment_type: &str,
    path_prefix: &str,
    max_footnote_chars: usize,
    find_section_fn: F,
) -> Result<(String, String), VerseToHtmlError>
where
    F: Fn(&str, &str, &str, &str) -> Option<usize>,
{
    let mut result_html = html.to_string();
    let mut fn_count: usize = 0;
    let mut fn_html = String::new();
    let mut search_ix: usize = 0;

    let is_oet_lv = version_abbrev == "OET-LV";
    let is_net = version_abbrev == "NET";
    let max_iter = if matches!(
        segment_type,
        "book" | "section" | "relatedPassage"
    ) {
        6_900
    } else {
        260
    };

    for _ in 0..max_iter {
        let f_start = match result_html[search_ix..].find("\\f ") {
            Some(ix) => search_ix + ix,
            None => break,
        };
        fn_count += 1;

        let f_end = result_html[f_start + 3..]
            .find("\\f*")
            .map(|ix| f_start + 3 + ix)
            .ok_or_else(|| VerseToHtmlError::MissingEndMarker {
                marker: "\\f*".into(),
                position: f_start + 3,
            })?;
        if f_end >= 9_999_999 {
            return Err(VerseToHtmlError::UnexpectedContent {
                details: format!("footnote end marker too far from start: {f_start}..{f_end}"),
            });
        }
        if f_end - f_start >= max_footnote_chars {
            return Err(VerseToHtmlError::UnexpectedContent {
                details: format!("footnote too large ({}) at position {f_start}", f_end - f_start),
            });
        }

        // --- Locate \fr (footnote reference, may be absent) ---
        let fr_ix = result_html[f_start + 3..]
            .find("\\fr ")
            .map(|ix| f_start + 3 + ix)
            .filter(|&ix| ix < f_end);

        // --- Find the first content marker: \f(something) or \xt ---
        let search_from = if let Some(fi) = fr_ix { fi + 3 } else { f_start + 3 };
        let f_content_ix = result_html[search_from..]
            .find("\\f")
            .map(|ix| search_from + ix)
            .filter(|&ix| ix < f_end);
        let x_content_ix = result_html[search_from..]
            .find("\\xt ")
            .map(|ix| search_from + ix)
            .filter(|&ix| ix < f_end);

        let first_content_ix = match (f_content_ix, x_content_ix) {
            (Some(f), Some(x)) => Some(f.min(x)),
            (Some(f), None) => Some(f),
            (None, Some(x)) => Some(x),
            (None, None) => None,
        };

        let first_content_ix = match first_content_ix {
            Some(ix) => ix,
            None => {
                // No internal markers found — skip past the `\f + ` or `\f ` prefix
                let prefix_len = if result_html[f_start..].starts_with("\\f + ") {
                    5
                } else {
                    3
                };
                f_start + prefix_len
            }
        };

        // --- Extract \fr text ---
        let fr_text = if let Some(fr_ix) = fr_ix {
            result_html[fr_ix + 3..first_content_ix].trim().to_string()
        } else {
            String::new()
        };

        // --- Extract the footnote middle content ---
        let mut fnote_middle = result_html[first_content_ix..f_end].to_string();

        // --- Process internal formatting markers ---
        let internal_open_count = count_internal_openers(&fnote_middle, is_net);
        if internal_open_count > 0 {
            process_internal_footnote_markers(
                &mut fnote_middle,
                version_abbrev,
                bbb,
                c,
                segment_type,
                path_prefix,
                &fr_text,
                is_net,
                &find_section_fn,
            )?;
        }

        // --- OET-LV period/colon protection ---
        if is_oet_lv {
            fnote_middle = fnote_middle
                .replace('.', "--fnPERIOD--")
                .replace(':', "--fnCOLON--");
        }

        // --- Sanitise the popup title text ---
        let sanitised = sanitise_footnote_popup(&fnote_middle, is_oet_lv);

        // --- Build the footnote caller ---
        let footnote_popup = if sanitised.len() < 1010 {
            sanitised.clone()
        } else {
            let truncated: String = sanitised.chars().take(999).collect();
            format!("{truncated}\u{2026}") // ellipsis
        };
        let caller = format!(
            r##"<span class="fnCaller">[<a title="{footnote_popup}" href="#fn{fn_count}">fn</a>]</span>"##
        );

        // --- Build the back-reference ---
        let fn_ref = build_footnote_ref(&fr_text);

        // --- OET-LV OSHB link ---
        let display_middle = if is_oet_lv && fnote_middle.starts_with("OSHB ") {
            fnote_middle.replacen(
                "OSHB ",
                r#"<a href="https://hb.OpenScriptures.org">OSHB</a> "#,
                1,
            )
        } else {
            fnote_middle.clone()
        };

        let fn_text = format!(
            r#"<p class="fn" id="fn{fn_count}">{fn_ref}<span class="fnText">{display_middle}</span></p><!--fn-->"#
        );

        // --- Duplicate detection (for parallel verses) ---
        if segment_type.ends_with("Verse") && fn_html.contains(&fn_text) {
            // Add an extra id span to the existing footnote
            if let Some(dup_ix) = fn_html.find(&fn_text) {
                let extra_id = format!(r#"><span id="fn{fn_count}"></span>"#);
                fn_html = format!(
                    "{}{}{}",
                    &fn_html[..dup_ix],
                    extra_id,
                    &fn_html[dup_ix + 2..]
                );
            }
        } else {
            fn_html.push_str(&fn_text);
            fn_html.push('\n');
        }

        // --- Replace the footnote in the HTML with the caller ---
        result_html = format!(
            "{}{}{}",
            &result_html[..f_start],
            caller,
            &result_html[f_end + 3..]
        );
        search_ix = f_start + caller.len();
    }

    Ok((result_html, fn_html))
}

/// Count internal opening markers in a footnote middle string.
fn count_internal_openers(fnote_middle: &str, is_net: bool) -> usize {
    let markers = [
        "\\ft ", "\\fq ", "\\fqa ", "\\fk ", "\\fl ", "\\fp ", "\\xt ",
        "\\it ", "\\bd ", "\\bdit ", "\\em ",
    ];
    let mut count = 0;
    for m in &markers {
        count += fnote_middle.matches(m).count();
    }
    if is_net {
        count += fnote_middle.matches("\\fn ").count();
    }
    count
}

/// Process internal formatting markers (`\ft`, `\fq`, `\it`, `\xt`, etc.)
/// inside a footnote, converting them to HTML `<span>` elements.
///
/// For `\xt` markers, the cross-reference text is livened via
/// `liven_xref_field_core`.
fn process_internal_footnote_markers<F>(
    fnote_middle: &mut String,
    version_abbrev: &str,
    bbb: &str,
    c: &str,
    segment_type: &str,
    path_prefix: &str,
    fr_text: &str,
    _is_net: bool,
    find_section_fn: &F,
) -> Result<(), VerseToHtmlError>
where
    F: Fn(&str, &str, &str, &str) -> Option<usize>,
{
    let mut in_span: Option<String> = None;
    let mut search_ix: usize = 0;

    for _ in 0..520 {
        let bs_ix = match fnote_middle[search_ix..].find('\\') {
            Some(ix) => search_ix + ix,
            None => break,
        };

        // Read the marker name (lowercase letters after '\')
        let mut marker_len: usize = 0;
        while bs_ix + marker_len + 1 < fnote_middle.len() {
            let ch = fnote_middle.as_bytes()[bs_ix + marker_len + 1];
            if ch.is_ascii_lowercase() {
                marker_len += 1;
            } else {
                break;
            }
        }
        let marker_name = fnote_middle[bs_ix + 1..bs_ix + 1 + marker_len].to_string();
        let next_char_pos = bs_ix + 1 + marker_len;
        if next_char_pos >= fnote_middle.len() {
            break;
        }
        let next_char = fnote_middle.as_bytes()[next_char_pos];

        if next_char == b' ' {
            // Opening marker
            let span_open = format!(r#"<span class="{marker_name}">"#);
            let mut replacement = String::new();

            if in_span.is_some() {
                replacement.push_str("</span>");
            }
            replacement.push_str(&span_open);

            if marker_name == "xt" {
                // Extract the \xt content and liven it
                let xt_content_start = bs_ix + marker_len + 2;
                let rest = &fnote_middle[xt_content_start..];
                let next_bs = rest.find('\\');
                let (xt_raw, continuation) = if let Some(nix) = next_bs {
                    (&rest[..nix], &rest[nix..])
                } else {
                    (rest, "")
                };
                let xt_text = xt_raw.to_string();
                let xt_continuation = continuation.to_string();

                let livened = liven_xref_field_core(
                    "f",
                    version_abbrev,
                    bbb,
                    c,
                    "",
                    segment_type,
                    path_prefix,
                    fr_text,
                    &xt_text,
                    find_section_fn,
                )
                .map_err(|e| VerseToHtmlError::CallbackFailed {
                    details: e.to_string(),
                })?;

                let new_middle = format!(
                    "{}{}{}{}",
                    &fnote_middle[..bs_ix],
                    replacement,
                    livened,
                    xt_continuation
                );
                search_ix = bs_ix + replacement.len() + livened.len();
                *fnote_middle = new_middle;
            } else {
                let tail = fnote_middle[bs_ix + 1 + marker_len + 1..].to_string();
                let new_middle = format!(
                    "{}{}{}",
                    &fnote_middle[..bs_ix],
                    replacement,
                    tail
                );
                search_ix = bs_ix + replacement.len();
                *fnote_middle = new_middle;
            }
            in_span = Some(marker_name);
        } else if next_char == b'*' {
            // Closing marker
            assert!(
                in_span.is_some(),
                "Closing marker without opening: \\{marker_name}*"
            );
            let new_middle = format!(
                "{}{}</span>{}",
                &fnote_middle[..bs_ix],
                "",
                &fnote_middle[bs_ix + 1 + marker_len + 1..]
            );
            *fnote_middle = new_middle;
            in_span = None;
            search_ix = bs_ix + 7; // len("</span>")
        } else {
            return Err(VerseToHtmlError::UnexpectedContent {
                details: format!(
                    "unexpected character after \\{marker_name} in footnote: '{}'",
                    next_char as char
                ),
            });
        }
    }

    // Close any unclosed span at the end
    if in_span.is_some() {
        fnote_middle.push_str("</span>");
    }

    Ok(())
}

/// Sanitise the footnote text for use in an HTML `title` attribute (popup).
fn sanitise_footnote_popup(fnote_middle: &str, is_oet_lv: bool) -> String {
    let mut s = fnote_middle.to_string();

    // Ensure "Note:" prefix
    if is_oet_lv {
        if !s.contains(" note--fnCOLON--") && !s.contains("Note--fnCOLON--") {
            s = format!("Note--fnCOLON-- {s}");
        }
    } else if !s.contains(" note:") && !s.contains("Note:") {
        s = format!("Note: {s}");
    }

    // Strip HTML if present
    if s.contains('"') || s.contains('<') || s.contains('>') {
        s = s.replace("</span>", "");
        s = SPAN_CLASS_REGEX.replace_all(&s, "").to_string();
        for tag in &["em", "i", "b", "sup", "sub"] {
            s = s.replace(&format!("<{tag}>"), "");
            s = s.replace(&format!("</{tag}>"), "");
        }
        if s.contains('"') || s.contains('<') || s.contains('>') {
            s = s.replace('"', "&quot;").replace('<', "&lt;").replace('>', "&gt;");
        }
    }

    if is_oet_lv {
        s = s
            .replace('.', "--fnPERIOD--")
            .replace(':', "--fnCOLON--")
            .replace('_', "--fnUNDERLINE--")
            .replace('=', "--fnEQUAL--");
    }

    s
}

/// Build a `<span class="fnRef">…</span>` back-reference from `\fr` text.
fn build_footnote_ref(fr_text: &str) -> String {
    if fr_text.is_empty() {
        return String::new();
    }
    let mut cv = fr_text.to_string();
    if cv.contains('-') || cv.contains('\u{2013}') {
        cv = cv.replace('\u{2013}', "-");
        if let Some(ix) = cv.find('-') {
            cv = cv[..ix].to_string();
        }
    }
    let href = if let Some(colon_ix) = cv.find(':') {
        let ch = &cv[..colon_ix];
        let v = &cv[colon_ix + 1..];
        format!("#C{ch}V{v}")
    } else if let Some(dot_ix) = cv.find('.') {
        let ch = &cv[..dot_ix];
        let v = &cv[dot_ix + 1..];
        format!("#C{ch}V{v}")
    } else {
        String::new()
    };
    format!(
        r#"<span class="fnRef"><a title="Return to text" href="{href}">{fr_text}</a></span> "#
    )
}

// ── PyO3 wrappers ─────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn noop_section(_v: &str, _b: &str, _c: &str, _v2: &str) -> Option<usize> {
        None
    }

    #[test]
    fn test_compute_path_prefix() {
        assert_eq!(compute_path_prefix("parallelVerse"), "../../OET/byC/");
        assert_eq!(compute_path_prefix("interlinearVerse"), "../../OET/byC/");
        assert_eq!(compute_path_prefix("topicalPassage"), "../OET/byC/");
        assert_eq!(compute_path_prefix("chapter"), "");
        assert_eq!(compute_path_prefix("book"), "../byC/");
        assert_eq!(compute_path_prefix("section"), "../byC/");
    }

    #[test]
    fn test_build_cv_ref_empty() {
        assert_eq!(build_cv_ref(""), "");
    }

    #[test]
    fn test_build_cv_ref_simple() {
        let result = build_cv_ref("1:1");
        assert!(result.contains("href=\"#C1V1\""));
        assert!(result.contains("1:1"));
    }

    #[test]
    fn test_build_cv_ref_with_range() {
        let result = build_cv_ref("1:1-3");
        assert!(result.contains("href=\"#C1V1\""));
    }

    #[test]
    fn test_build_cv_ref_with_endash() {
        let result = build_cv_ref("1:1\u{2013}3");
        assert!(result.contains("href=\"#C1V1\""));
    }

    #[test]
    fn test_build_footnote_ref_empty() {
        assert_eq!(build_footnote_ref(""), "");
    }

    #[test]
    fn test_build_footnote_ref_colon() {
        let result = build_footnote_ref("3:16");
        assert!(result.contains("href=\"#C3V16\""));
        assert!(result.contains("3:16"));
    }

    #[test]
    fn test_build_footnote_ref_dot() {
        let result = build_footnote_ref("3.16");
        assert!(result.contains("href=\"#C3V16\""));
    }

    #[test]
    fn test_build_footnote_ref_range() {
        let result = build_footnote_ref("3:16-17");
        assert!(result.contains("href=\"#C3V16\""));
    }

    #[test]
    fn test_count_internal_openers_basic() {
        assert_eq!(count_internal_openers("\\ft Some text here", false), 1);
        assert_eq!(count_internal_openers("\\ft Text \\fq Quote", false), 2);
        assert_eq!(count_internal_openers("No markers here", false), 0);
    }

    #[test]
    fn test_count_internal_openers_net() {
        assert_eq!(count_internal_openers("\\ft Text \\fn Note", true), 2);
        assert_eq!(count_internal_openers("\\ft Text \\fn Note", false), 1);
    }

    #[test]
    fn test_process_xrefs_simple() {
        let html = r#"Some text \x \xo 1:1 \xt Gen 1:1.\x* more text"#;
        let (result, xr) = process_cross_references_core(
            html, "KJB", "GEN", "1", "chapter", "../byC/", noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\x "));
        assert!(result.contains("xrCaller"));
        assert!(xr.contains("xrText"));
    }

    #[test]
    fn test_process_xrefs_no_xo() {
        let html = r#"Text \x \xt John 3:16.\x* end"#;
        let (result, xr) = process_cross_references_core(
            html, "KJB", "JHN", "3", "chapter", "../byC/", noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\x "));
        assert!(xr.contains("xrText"));
    }

    #[test]
    fn test_process_xrefs_none_present() {
        let html = "No cross-references here.";
        let (result, xr) = process_cross_references_core(
            html, "KJB", "GEN", "1", "chapter", "../byC/", noop_section,
        )
        .unwrap();
        assert_eq!(result, html);
        assert!(xr.is_empty());
    }

    #[test]
    fn test_process_xrefs_multiple() {
        let html = r#"First \x \xo 1:1 \xt Gen 1:1.\x* and second \x \xo 2:3 \xt Gen 2:3.\x* done"#;
        let (result, xr) = process_cross_references_core(
            html, "KJB", "GEN", "1", "chapter", "../byC/", noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\x "));
        // Both xrefs should be collected
        assert!(xr.contains("xr1"));
        assert!(xr.contains("xr2"));
    }

    #[test]
    fn test_sanitize_footnote_popup_basic() {
        let result = sanitise_footnote_popup("Some text here", false);
        assert!(result.starts_with("Note: "));
    }

    #[test]
    fn test_sanitize_footnote_popup_oet_lv() {
        let result = sanitise_footnote_popup("Some text", true);
        assert!(result.starts_with("Note--fnCOLON-- "));
    }

    #[test]
    fn test_sanitize_footnote_popup_html_stripped() {
        let result = sanitise_footnote_popup("Text with <b>bold</b> and \"quotes\"", false);
        assert!(!result.contains('<'));
        assert!(!result.contains('"'));
        assert!(result.contains("bold"));
    }

    #[test]
    fn test_process_footnotes_none_present() {
        let html = "No footnotes here.";
        let (result, fn_html) = process_footnotes_core(
            html, "KJB", "GEN", "1", "chapter", "../byC/", 11_500, noop_section,
        )
        .unwrap();
        assert_eq!(result, html);
        assert!(fn_html.is_empty());
    }

    #[test]
    fn test_process_footnotes_simple() {
        let html = r#"Text \f + \fr 1:1 \ft Footnote content.\f* here"#;
        let (result, fn_html) = process_footnotes_core(
            html, "KJB", "GEN", "1", "chapter", "../byC/", 11_500, noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\f "));
        assert!(result.contains("fnCaller"));
        assert!(fn_html.contains("fnText"));
        assert!(fn_html.contains("Footnote content."));
    }

    #[test]
    fn test_process_footnotes_empty_c() {
        let html = r#"Text \f + \fr 3:16 \ft God so loved.\f* here"#;
        let (result, fn_html) = process_footnotes_core(
            html, "KJB", "JHN", "", "book", "../byC/", 11_500, noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\f "));
        assert!(result.contains("fnCaller"));
        assert!(fn_html.contains("fnText"));
        assert!(fn_html.contains("God so loved."));
    }

    #[test]
    fn test_process_xrefs_empty_c() {
        let html = r#"Text \x \xo 1:1 \xt Gen 1:1.\x* end"#;
        let (result, xr) = process_cross_references_core(
            html, "KJB", "GEN", "", "book", "../byC/", noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\x "));
        assert!(result.contains("xrCaller"));
        assert!(xr.contains("xrText"));
    }

    #[test]
    fn test_footnote_internal_marker_at_end() {
        let html = r#"Text \f + \fr 1:1 \ft See \it this.\f*"#;
        let (result, fn_html) = process_footnotes_core(
            html, "ULT", "MRK", "1", "chapter", "", 11_500, noop_section,
        )
        .unwrap();
        assert!(!result.contains("\\f "));
        assert!(result.contains("fnCaller"));
        assert!(fn_html.contains("fnText"));
        assert!(fn_html.contains("<span class=\"it\">"));
        assert!(fn_html.contains("</span>"));
    }
}
